name: Go

on: push

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
